### ISSUE TITLE
Doesn't work with IE11

### ISSUE THREAD

**Issue by marcohamersma** [75lb/wordwrapjs#5]
Our web app broke in IE11 when we included this module, because it trips over the ES6 Class syntax. 

Considering that it's customary that Babel ignore the `node_modules` folder, would it be possible that the NPM version of this package uses an ES5-compatible version, like many other libraries do? I found [this article](https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/) but there's probably more recent ones as well.

**Comment by 75lb** [comment]
sorry, I don't support ES5..
