### ISSUE TITLE
Adding functionality and optional nomenclature from word-wrap

### ISSUE THREAD

**Issue by jls47** [75lb/wordwrapjs#9]
It looks like the word-wrap package is not being maintained anymore, as it's been 6 years since the last update and there's a pull request to address a security concern that's been waiting to be merged for close to half a year now.  It may get approved at some point but I think it makes more sense to start making some updates here where there isn't a vulnerable regex at the heart of everything.

I've gone ahead and added the two bits of functionality word-wrap had that this didn't (indents and escape functions), as well as adding support for the word-wrap option names into existing functions and new tests all around to make sure things work as expected. #10

**Comment by 75lb** [comment]
Hi, sorry for the slow reply. Thanks for the suggested improvements. 

Regarding `cut`, `newline` and `trim`, I'd rather add a compatibility note in the readme than track, mimic and maintain a third party's semantics and naming choices - which may change or die. 

Regarding `indent` and `escape` - the [.lines()](https://github.com/75lb/wordwrapjs?tab=readme-ov-file#wordwraplinestext-options) method already returns an array which can be manipulated in any way the user sees fit, including prefixing, suffixing etc.

I won't be merging this time but the suggestions were food for thought, thanks.

**Comment by jls47** [comment]
Blast from the past!  I appreciate the feedback, as sort of goofy as this PR was, in hindsight.
